# Site settings
title: Nate Berkopec
email: nate.berkopec@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The blog of Nate Berkopec, Ruby on Rails programmer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.nateberkopec.com" # the base hostname & protocol for your site
author: Nate Berkopec
# Build settings
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
future:      false
unpublished: false
permalink: "blog/:title/"
encoding: utf-8

post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: subl
git:
  branch: master

plugins:
  - jekyll-postcss-v2

postcss:
  script: node_modules/.bin/postcss
  config: postcss.config.js

sass:
  style: compressed
